### ISSUE TITLE
svn links dont exist anymore.

### ISSUE THREAD

**Issue by KeksNino** [NyarchLinux/Nyarcher#6]
all the github links in the install script dont work anymore. f.e.: svn checkout https://github.com/NyarchLinux/NyarchLinux/trunk/Gnome/etc/skel/.local/share/backgrounds doesnt exist anymore and makes the script not work properly

**Comment by KeksNino** [comment]
svn: E170013: Unable to connect to a repository at URL 'https://github.com/NyarchLinux/NyarchLinux/trunk/Gnome/etc/skel/.local/share/backgrounds'
svn: E160013: '/NyarchLinux/NyarchLinux/trunk/Gnome/etc/skel/.local/share/backgrounds' path not found

**Comment by FrancescoCaracciolo** [comment]
Duplicate of #4
