### ISSUE TITLE
None of the app installed from flatpak opens, nor the nyarch ones

### ISSUE THREAD

**Issue by ReLyf47** [NyarchLinux/Nyarcher#7]
installing stuff using the nyarcher script makes app not work
reinstalling the app but just straight from flathub (not cli) works fine

**Comment by FrancescoCaracciolo** [comment]
That's weird, on which distro are you trying to install?

**Comment by ReLyf47** [comment]
oh weird i guess its something with my arch install, now it doesnt work

**Comment by ReLyf47** [comment]
> That's weird, on which distro are you trying to install?

just plain arch

**Comment by FrancescoCaracciolo** [comment]
ok, please note that at the moment Nyarcher is outdated so almost everything does not work

**Comment by ReLyf47** [comment]
yeah the only thing i managed to get to work is just kitty

**Comment by ReLyf47** [comment]
well incase anyone wondering why
its something with wayland not wanting every app that nyarcher install to run

doing `GSK_RENDERER=gl flatpak run app-name` solves it
but i guess its not a nyarch issue more of a gtk/gsk/wayland thing
